apiVersion: batch/v1
kind: CronJob
metadata:
  name: sellout
  namespace: sellout
spec:
  schedule: "1 * * * *"
  jobTemplate:
    spec:
      backoffLimit: 0
      template:
        spec:
          restartPolicy: Never
          containers:
            - name: sellout
              image: sellout:dev
              imagePullPolicy: IfNotPresent
              envFrom:
                - secretRef:
                    name: sellout-db
              env:
                - name: DIR_BASE
                  value: "/Volumes"
                - name: DIR_ENTRADA
                  value: "reveived"
                - name: DIR_SALIDA
                  value: "done2"
                - name: INPUT_DIR
                  value: "/Volumes/archivos"
                - name: DONE_DIR
                  value: "/Volumes/resultados"
              volumeMounts:
                - name: received
                  mountPath: /Volumes/received
                - name: done
                  mountPath: /Volumes/done
          volumes:
            - name: received
              hostPath:
                path: /Volumes/received
                type: Directory
            - name: done
              hostPath:
                path: /Volumes/done
                type: Directory
env:
  - name: DIR_BASE
    value: "/Volumes"
  - name: DIR_ENTRADA
    value: "archivos"
  - name: DIR_SALIDA
    value: "resultados"
  - name: INPUT_DIR
    value: "/Volumes/archivos"
  - name: DONE_DIR
    value: "/Volumes/resultados"