apiVersion: batch/v1
kind: CronJob
metadata:
  name: sellout
  namespace: sellout
spec:
  schedule: "1 * * * *"
  jobTemplate:
    spec:
      backoffLimit: 0
      template:
        spec:
          restartPolicy: Never
          containers:
            - name: sellout
              image: sellout:dev
              imagePullPolicy: IfNotPresent
              envFrom:
                - secretRef:
                    name: sellout-db
              env:
                - name: DIR_BASE
                  value: "/Volumes"
                - name: DIR_ENTRADA
                  value: "archivos"
                - name: DIR_SALIDA
                  value: "done"
              volumeMounts:
                - name: archivos
                  mountPath: /Volumes/archivos
                - name: done
                  mountPath: /Volumes/done
          volumes:
            - name: archivos
              hostPath:
                path: /Volumes/archivos
                type: Directory
            - name: done
              hostPath:
                path: /Volumes/done
                type: Directory
