apiVersion: v1
kind: Secret
metadata:
  name: sellout-db
  namespace: sellout
type: Opaque
stringData:
  DB_HOST: "host.docker.internal"
  DB_PORT: "5432"
  DB_NAME: "dwh"
  DB_USER: "dwh"
  DB_PASSWORD: "dwh_bts"